AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a .NET WebApi on AWS Fargate that talks to Aurora, hosted in a private subnet/FARGATE accessible via a public load balancer.
Mappings:  
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0b69ea66ff7391e80   
    us-east-2:
      HVM64: ami-00c03f7f7f2ec15c3
    us-west-1:
      HVM64: ami-0245d318c6788de52
    us-west-2:
      HVM64: ami-04b762b4289fba92b
    ap-south-1:
      HVM64: ami-0cb0e70f44e1a4bb5
      
Parameters:
  StackName:
    Type: String
    Default: user-bff-stack-infra
    Description: The name of the parent stack that spun up infrastructure already
  AppStackName:
    Description: Service stack for net-core-task
    Type: String
    Default: user-bff-stack-service

Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${AppStackName}-user-bff-service
      Cluster:
        Fn::ImportValue:
          !Join [':', [!Ref 'StackName', 'ClusterName']]
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Join [':', [!Ref 'StackName', 'ECSSecurityGroup']]
          Subnets:
            - Fn::ImportValue:
                !Join [':', [!Ref 'StackName', 'PublicSubnet1']]
            - Fn::ImportValue:
                !Join [':', [!Ref 'StackName', 'PublicSubnet2']]

      TaskDefinition: 
        Fn::ImportValue:
          !Join [':', [!Ref 'StackName', 'ECSTaskDefinition']] 
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 80
          TargetGroupArn:
            Fn::ImportValue:
              !Join [':', [!Ref 'StackName', 'TargetGroupName']]

Outputs:
  HealthCheckUrl:
    Description: Healthcheck URL
    Value: 
       Fn::Join:
        - ''
        - - Fn::ImportValue:
              !Join [':', [!Ref 'StackName', 'ExternalUrl']] 
          - '/api/values'
  WebApiUrl:
    Description: WebApi URL
    Value: 
       Fn::Join:
        - ''
        - - Fn::ImportValue:
              !Join [':', [!Ref 'StackName', 'ExternalUrl']] 
          - '/api/'